/**
https://www.bottlecaps.de/rr/ui
**/

Selector
  ::= SelectorElement*

SelectorElement
  ::= FlatSelectorElement
    | DeepSelectorElement

FlatSelectorElement
  ::= '>' ElementMatcher

DeepSelectorElement
  ::= '~' ElementMatcher

ElementMatcher
  ::= NameElementMatcher
    | DeepElementMatcher

NameElementMatcher
  ::= Char* ( '{' Expression '}' )?

DeepElementMatcher
  ::= '*' ( '{' Expression '}' )?

Expression
  ::= TODO
